-- ============================================================
-- WeatherGPT — Database Schema
-- Run this in your Supabase SQL Editor (Settings → SQL Editor)
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── Users ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name                 TEXT        NOT NULL,
    email                TEXT        UNIQUE NOT NULL,
    password_hash        TEXT        NOT NULL,
    role                 TEXT        NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    phone_number         TEXT,
    phone_verified       BOOLEAN     NOT NULL DEFAULT false,
    whatsapp_consent     BOOLEAN     NOT NULL DEFAULT false,
    whatsapp_consent_at  TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Locations (global de-duplicated by lat/lng) ───────────────────────────────
CREATE TABLE IF NOT EXISTS locations (
    id         UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT  NOT NULL,
    latitude   FLOAT NOT NULL,
    longitude  FLOAT NOT NULL,
    UNIQUE (latitude, longitude)
);

-- ── User-saved locations (many-to-many join with extras) ──────────────────────
CREATE TABLE IF NOT EXISTS user_locations (
    id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    location_id UUID    NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    label       TEXT,
    is_default  BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (user_id, location_id)
);

-- ── Weather data cache (current conditions) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS weather_data (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    location_id UUID        NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    fetched_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_json    JSONB       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_weather_data_location_fetched
    ON weather_data(location_id, fetched_at DESC);

-- ── Forecast cache ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS forecasts (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    location_id   UUID        NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    forecast_type TEXT        NOT NULL CHECK (forecast_type IN ('hourly', 'daily', 'extended')),
    fetched_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_json      JSONB       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_forecasts_location_type
    ON forecasts(location_id, forecast_type, fetched_at DESC);

-- ── Alert subscriptions (what the user wants to be notified about) ────────────
CREATE TABLE IF NOT EXISTS alert_subscriptions (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    location_id     UUID        NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    event_type      TEXT        NOT NULL CHECK (event_type IN ('rain', 'heat', 'cold', 'storm', 'wind', 'uv', 'aqi')),
    threshold_value FLOAT,
    enabled         BOOLEAN     NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Alerts (generated by the alert engine) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS alerts (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    location_id UUID        NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    event_type  TEXT        NOT NULL,
    severity    TEXT        NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    message     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alerts_user_expires
    ON alerts(user_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_active
    ON alerts(user_id, location_id, event_type, expires_at);

-- ── Notification preferences (per user) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS notification_preferences (
    id                   UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id              UUID    UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    push_enabled         BOOLEAN NOT NULL DEFAULT true,
    whatsapp_enabled     BOOLEAN NOT NULL DEFAULT false,
    in_app_enabled       BOOLEAN NOT NULL DEFAULT true,
    daily_briefing_time  TIME,
    min_severity         TEXT    NOT NULL DEFAULT 'WARNING'
                                 CHECK (min_severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

-- ── Web Push subscriptions (browser push like Zomato/Swiggy) ─────────────────
--   One user can have multiple subscriptions (different devices/browsers)
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint    TEXT        NOT NULL UNIQUE,
    p256dh      TEXT        NOT NULL,
    auth        TEXT        NOT NULL,
    user_agent  TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_push_subs_user ON push_subscriptions(user_id);

-- ── WhatsApp messages log ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS whatsapp_messages (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    alert_id      UUID        REFERENCES alerts(id) ON DELETE SET NULL,
    template_name TEXT        NOT NULL,
    status        TEXT        NOT NULL DEFAULT 'queued'
                              CHECK (status IN ('queued', 'sent', 'delivered', 'read', 'failed')),
    attempt_count INT         NOT NULL DEFAULT 0,
    provider_msg_id TEXT,
    sent_at       TIMESTAMPTZ,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Notification logs (audit trail for all channels) ─────────────────────────
CREATE TABLE IF NOT EXISTS notification_logs (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    alert_id     UUID        REFERENCES alerts(id) ON DELETE SET NULL,
    channel      TEXT        NOT NULL CHECK (channel IN ('push', 'whatsapp', 'in_app')),
    status       TEXT        NOT NULL,
    error_detail TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_notif_logs_user
    ON notification_logs(user_id, created_at DESC);

-- ── Climate / historical averages (seeded per location per month) ─────────────
CREATE TABLE IF NOT EXISTS climate_data (
    id           UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
    location_id  UUID  NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    month        INT   NOT NULL CHECK (month BETWEEN 1 AND 12),
    avg_temp     FLOAT,
    avg_rainfall FLOAT,
    UNIQUE (location_id, month)
);

-- ── AI conversation history ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_conversations (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    location_id UUID        REFERENCES locations(id) ON DELETE SET NULL,
    role        TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
    message     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ai_conv_user
    ON ai_conversations(user_id, created_at DESC);

-- ── OTP store (phone number verification) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS otp_store (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    otp_code   TEXT        NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used       BOOLEAN     NOT NULL DEFAULT false
);

-- ============================================================
-- Row Level Security (enable after initial setup if using Supabase RLS)
-- For service-role key access, RLS is bypassed automatically.
-- ============================================================
